---
- name: DockerGitLabPlaybook
  hosts: dockergitlabhosts
  become: true
  remote_user: root
  gather_facts: true
  vars_files:
    - ./vars/main.yml
  roles:
    - role: base
    - role: add_users
    - role: sysctl
    - role: docker
    - role: docker_gitlab_deploy
  environment: "{{ proxy_env }}"
